package web

import (
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/CycSpring/SpringX-Scanner/internal/model"
)

// scanResponse is returned by POST /api/scan. The job_id is generated by the
// WebUI up front so the client can subscribe to the SSE stream immediately,
// before the engine scan_id is known (it arrives with scan_started).
type scanResponse struct {
	JobID string `json:"job_id"`
}

// handleStartScan accepts a JSON ScanRequest, launches a scan child process,
// and returns its job_id.
func (s *Server) handleStartScan(w http.ResponseWriter, r *http.Request) {
	var req ScanRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid JSON body: "+err.Error())
		return
	}
	if req.URL == "" && req.IP == "" && req.URLFile == "" && req.IPFile == "" {
		writeError(w, http.StatusBadRequest, "at least one of url, ip, urlfile, ipfile is required")
		return
	}
	job, err := s.mgr.Start(r.Context(), req)
	if err != nil {
		writeError(w, http.StatusInternalServerError, err.Error())
		return
	}
	writeJSON(w, http.StatusOK, scanResponse{JobID: job.id})
}

// handleListScans returns all known scan jobs.
func (s *Server) handleListScans(w http.ResponseWriter, _ *http.Request) {
	writeJSON(w, http.StatusOK, s.mgr.List())
}

// handleEvents is the SSE endpoint. It replays the job's cached event history
// (the source of truth) then streams live events until terminal.
func (s *Server) handleEvents(w http.ResponseWriter, r *http.Request) {
	jobID := r.URL.Query().Get("id")
	if jobID == "" {
		writeError(w, http.StatusBadRequest, "missing id query parameter")
		return
	}
	job := s.mgr.Get(jobID)
	if job == nil {
		writeError(w, http.StatusNotFound, "scan job not found")
		return
	}
	s.serveSSE(w, r, job)
}

// handleCancelScan gracefully stops a running scan.
func (s *Server) handleCancelScan(w http.ResponseWriter, r *http.Request) {
	jobID := r.PathValue("jobID")
	if err := s.mgr.Cancel(jobID); err != nil {
		switch err {
		case ErrJobNotFound:
			writeError(w, http.StatusNotFound, err.Error())
		case ErrJobNotRunning:
			writeError(w, http.StatusConflict, err.Error())
		default:
			writeError(w, http.StatusInternalServerError, err.Error())
		}
		return
	}
	writeJSON(w, http.StatusOK, map[string]string{"status": "cancelling"})
}

// reportListItem is the metadata returned by GET /api/reports. It is derived
// from the on-disk JSON report (a model.Result) so the list view shows counts.
type reportListItem struct {
	Name      string    `json:"name"`
	ScanID    string    `json:"scan_id,omitempty"`
	StartedAt time.Time `json:"started_at,omitempty"`
	Status    string    `json:"status,omitempty"`
	Targets   int       `json:"targets"`
	Vulns     int       `json:"vulns"`
	Size      int64     `json:"size"`
	Modified  time.Time `json:"modified"`
}

// handleListReports scans reports/data/*.json (basename only) under the work
// directory and returns metadata sorted by mtime, newest first.
func (s *Server) handleListReports(w http.ResponseWriter, _ *http.Request) {
	dir := s.reportsDataDir()
	entries, err := os.ReadDir(dir)
	if err != nil {
		// No reports yet is not an error.
		writeJSON(w, http.StatusOK, []reportListItem{})
		return
	}
	items := make([]reportListItem, 0, len(entries))
	for _, e := range entries {
		if e.IsDir() || !strings.HasSuffix(e.Name(), ".json") {
			continue
		}
		full := filepath.Join(dir, e.Name())
		info, err := e.Info()
		if err != nil {
			continue
		}
		item := reportListItem{
			Name:     e.Name(),
			Size:     info.Size(),
			Modified: info.ModTime(),
		}
		if res := readResultSummary(full); res != nil {
			item.ScanID = res.Scan.ID
			item.StartedAt = res.Scan.StartedAt
			item.Status = res.Scan.Status
			item.Targets = len(res.Targets)
			item.Vulns = len(res.Vulnerabilities)
		}
		items = append(items, item)
	}
	sort.Slice(items, func(i, j int) bool { return items[i].Modified.After(items[j].Modified) })
	writeJSON(w, http.StatusOK, items)
}

// handleGetReport returns a single JSON report by basename. The :name path
// segment is sanitized to its base and the resolved path is verified to stay
// within reports/data, preventing ../ and absolute-path traversal.
func (s *Server) handleGetReport(w http.ResponseWriter, r *http.Request) {
	name := r.PathValue("name")
	if name == "" {
		writeError(w, http.StatusBadRequest, "missing report name")
		return
	}
	base := filepath.Base(name)
	if base != name || strings.ContainsAny(base, `/\`) || base == "." || base == ".." {
		writeError(w, http.StatusBadRequest, "invalid report name")
		return
	}
	dir := s.reportsDataDir()
	full := filepath.Join(dir, base)
	rel, err := filepath.Rel(dir, full)
	if err != nil || rel != base {
		writeError(w, http.StatusNotFound, "report not found")
		return
	}
	data, err := os.ReadFile(full)
	if err != nil {
		writeError(w, http.StatusNotFound, "report not found")
		return
	}
	w.Header().Set("Content-Type", "application/json")
	w.Header().Set("Cache-Control", "no-cache")
	_, _ = w.Write(data)
}

// reportsDataDir is the absolute path to reports/data under the work dir.
func (s *Server) reportsDataDir() string { return filepath.Join(s.workDir, "reports", "data") }

// readResultSummary reads just enough of a report JSON to populate list
// metadata. A malformed file yields nil (skipped).
func readResultSummary(path string) *model.Result {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil
	}
	var res model.Result
	if err := json.Unmarshal(data, &res); err != nil {
		return nil
	}
	return &res
}

// writeJSON marshals v as JSON with the given status.
func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	_ = json.NewEncoder(w).Encode(v)
}

// writeError writes a small JSON error object.
func writeError(w http.ResponseWriter, status int, msg string) {
	writeJSON(w, status, map[string]string{"error": msg})
}
